version: "3.3"
services:
  postgres:
    image: postgres:13
    environment:
      - POTGRESS_DB=my_store
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
